name: tex-thesis

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Build PDFs
      run: DOCKER_BUILDKIT=1 docker build --output type=local,dest=out .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: thesis-pdfs
        path: |
          out/thesis.pdf
          out/slides/slides.pdf

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          out/thesis.pdf
          out/slides/slides.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
